import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ tree; ordering/labels come from each folder's
// _category_.json (synced from ds01-infra/docs-user/).
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
